name: Deploy Development

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-laravel.yml
    with:
      environment_name: development
      deploy_path: /home/dev.laravel-project.com/public
      site_user: devla3594
      port: 8080
    secrets: inherit
