name: Deploy Production

on:
  push:
    branches:
      - prod
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-laravel.yml
    with:
      environment_name: production
      deploy_path: /home/prod.laravel-project.com/public
      site_user: prodl5985
      port: 80
    secrets: inherit
